name: RecipeUtil Testing
description: Testing RecipeUtil class
version: 1.0
author: Digi
main: ro.thehunters.digi.recipeUtil.testing.Testing
commands:
  test:
    description: test
    usage: /<command>